### ISSUE TITLE
Linux Support for Desktop App

### ISSUE THREAD

**Issue by poeck** [LogSnag/LogSnag#2]
Will the desktop app also be available on Linux in the future?
I think the app doesn't have too many native features, so it might just need to be built for Linux.
Since many developers also use LogSnag, I think a considerable number of users are on Linux.

**Comment by poeck** [comment]
Just found out there are actually Linux Builds in [here](https://github.com/LogSnag/LogSnag/releases/tag/v1.1.7).
In this case, I think it should be mentioned on the [Download Page](https://logsnag.com/download) too.

**Comment by Sh4yy** [comment]
Thanks for the feedback! I will add the linux builds to our download page.

Closing this issue.
